# Imports
import glob
import os
import socket
import sys
import re
import unittest

# Constants
adguard_input_fn = 'data/input/adguard.txt'

# Classes


class AdguardPatternChecker:
    def __init__(self, patterns: list):
        """Initialize with precompiled regex patterns"""
        self.compiled_patterns = [re.compile(adguard_pattern.replace('||', r'(^|\.)').rstrip(
            '^') + '$', re.IGNORECASE) for adguard_pattern in patterns]

    def check_fqdn(self, fqdn: str) -> bool:
        """Check if FQDN matches any of the precompiled patterns"""
        return any(pattern.search(fqdn) for pattern in self.compiled_patterns)


class TestPrepareFinalLists(unittest.TestCase):
    def test_check_fqdn_against_adguard(self):
        test_cases = (
            ('blog.example.org', ['||example.org^'], True),
            ('example.org', ['||example.org^'], True),
            ('barexample.org', ['||example.org^'], False),
            ('example.com', ['||example.org^'], False),
            ('example.org.uk', ['||example.org^'], False),
        )
        for fqdn, patterns, expected in test_cases:
            with self.subTest(fqdn=fqdn, patterns=patterns, expected=expected):
                adguard_checker = AdguardPatternChecker(patterns)
                self.assertEqual(adguard_checker.check_fqdn(fqdn), expected)

    def test_sort_fqdns(self):
        fqdns = ['blog.example.com', 'mail.example.com', 'api.example.org', 'docs.example.org']
        self.assertEqual(sort_fqdns(fqdns), fqdns)
        self.assertEqual(sort_fqdns(fqdns[::-1]), fqdns)
        self.assertEqual(sort_fqdns([]), [])
        # using list comprehension to make new list, for each element in fqdns, prefix with '||' and suffix with '^'
        adguard_list = ['||' + fqdn + '^' for fqdn in fqdns]
        self.assertEqual(sort_fqdns(adguard_list), adguard_list)
        self.assertEqual(sort_fqdns(adguard_list[::-1]), adguard_list)

# Functions


def add_new_hostnames_to_file(dst_fn, get_subdomains_func, *args):
    """
    Add new hostnames to a file.

    The file must already exist.
    """
    full_fn = os.path.join('data/input/hostname_ip', dst_fn)
    known_hostnames = read_hostnames_from_file(full_fn)
    print(f'* count of known hostnames: {len(known_hostnames)}')

    api_hostnames = get_subdomains_func(*args)
    print(f'* count of API hostnames: {len(api_hostnames)}')

    new_hostnames = set(api_hostnames) - set(known_hostnames)

    if not new_hostnames:
        print('* no new hostnames found')
        return

    print(f'* writing  {len(new_hostnames)} new hostnames to {full_fn}')
    with open(full_fn, 'a', encoding="utf-8") as file:
        for hostname in sorted(new_hostnames):
            file.write(f'{hostname}\n')


def clean_line(line: str) -> str:
    """Remove comments and whitespace from line"""
    return line.strip('\n').split('#')[0].split(',')[0].strip()


def read_hostnames_from_file(filename: str) -> list:
    """Return every unique hostname from input file"""
    print(f'reading hosts from {filename}')
    hostnames = set()
    with open(filename, 'r', encoding='utf-8') as file:
        for line in file:
            hostname = clean_line(line)
            if '-tor.' in hostname:  # example: hostname=us-co-21-tor.protonvpn.net
                # print(f'WARNING: skipping tor: {hostname}')
                continue
            if hostname:
                hostnames.add(hostname)
    return list(hostnames)


def read_input_hostnames(input_hostname_pattern) -> list:
    """Return every unique hostname from input directory (multiple files)"""
    hostnames = set()
    for filename in glob.glob(input_hostname_pattern):
        hostnames.update(read_hostnames_from_file(filename))
    return list(hostnames)


def resolve_hostname(hostname: str) -> list:
    """Return a list of IPv4 IPs for the given hostname

    If there is an error resolving the hostname, return an empty list

    """
    # print(f'INFO: resolving hostname {hostname}')
    try:
        ip_addresses = socket.getaddrinfo(
            hostname, None, family=socket.AF_INET)
    except socket.gaierror as e:
        # print(f"ERROR: Error resolving {hostname}: {e}")
        return []
    ret = {ip[4][0] for ip in ip_addresses}
    return list(ret)


def sort_fqdns(fqdns: list) -> list:
    """Sort fully qualified domain names with reversed parts

    Example result:
    blog.example.com
    mail.example.com    
    api.example.org
    docs.example.org

    Sorting reduces the size of the diff.
    """
    return sorted(fqdns, key=lambda fqdn: fqdn.lower().split('.')[::-1])


def write_hostnames_to_text_file(filename, hostnames):
    assert isinstance(filename, str)
    assert isinstance(hostnames, list)
    print(f'writing {len(hostnames):,} hostnames to {filename}')
    with open(filename, "w", encoding="utf-8") as file:
        file.write(f'# This file was automatically generated by {sys.argv[0]}\n')
        file.write('\n'.join(hostnames))
        file.write('\n')

# Main Execution Logic (if any)
# Add any script logic here if needed
