name: Update data regularly
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1,13 * * *' # Runs twice each day
jobs:
  update:
    name: Update data
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      IS_INTERACTIVE: 0 # 0=headless
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run code
        run: |
            chmod +x update.sh
            ./update.sh
        shell: bash
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Update data
          add: 'data/*txt'
          author_name: 'automatic'
          author_email: 'actions@github.com'