name: Update data daily
on:
  schedule:
    - cron: '0 1,13 * * *' # Runs twice each day
jobs:
  update:
    name: Update data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run code
        run: |
            chmod +x update.sh
            ./update.sh
        shell: bash
      - name: Commit changes
        uses: EndBug/add-and-commit@v7.0.0
        with:
          message: Update data
          add: 'data/*txt'
          author_name: 'automatic'
          author_email: 'actions@github.com'

