name: Update data regularly
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1,13 * * *' # Runs twice each day
jobs:
  update:
    name: Update data
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run code
        run: |
            chmod +x update.sh
            ./update.sh
        shell: bash
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Update data
          add: 'data/*txt'
          author_name: 'automatic'
          author_email: 'actions@github.com'
      - name: Upload ip cache to R2
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: data/cache
          destination-dir: ./
      - name: Upload static site to R2
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: site
          destination-dir: ./
      - name: Upload data/output to R2
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: data/output
          destination-dir: ./