name: Update data daily
on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
jobs:
  update:
    name: Update data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Python script
        run: python hostname_to_ip.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v7.0.0
        with:
          message: Update data
          add: 'data/*txt'
          author_name: 'automatic'
          author_email: 'actions@github.com'

